name: Build and Publish
on: [push, pull_request]
jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn
      - run: yarn build
      - run: yarn build:types

      # Publish github
      - name: Github Publish
        if: startsWith(github.ref, 'refs/tags/v')
        run: yarn publish
        env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Github prepublish as branch
        if: startsWith(github.ref, 'refs/tags/v')
        id: github-prepush
        run: |
          mkdir publish
          cp -r dist publish
          cp -r types publish
          cp package.json publish
          echo "::set-output name=msg::$(git describe --tags)"

      - name: Github publish as branch
        if: startsWith(github.ref, 'refs/tags/v')
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: package
          build_dir: publish
          commit_message: ${{ steps.github-prepush.outputs.msg }}
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  storybook:
    name: Build Storybook
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn
      - run: yarn build:storybook

      # Publish build
      - name: Set commit message
        if: startsWith(github.ref, 'refs/tags/v')
        id: commit-message
        run: echo "::set-output name=msg::$(date)"
      - name: Push to gh-pages
        if: startsWith(github.ref, 'refs/tags/v')
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: storybook-static
          commit_message: ${{ steps.commit-message.outputs.msg }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
